version: 2

sources:
  - name: sap
    description: Fonte de dados da Adventure Works
    schema: sap_adw

    tables:
      - name: address
        description: Street address information for customers, employees, and vendors

      - name: countryregion
        description: Lookup table containing the ISO standard codes for countries and regions

      - name: creditcard
        description: Customer credit card information

      - name: customer
        description: Current customer information

      - name: person
        description: Human beings involved with AdventureWorks employees, customer contacts, and vendor contacts

      - name: product
        description: Products sold or used in the manfacturing of sold products
        columns:
          - name: productid
            description: Primary key for Product records
            tests:
              - unique
              - not_null
    
      - name: salesorderdetail
        description: Individual products associated with a specific sales order

      - name: salesorderheader
        description: General sales order information
      
      - name: salesorderheadersalesreason
        description: Cross-reference table mapping sales orders to sales reason codes

      - name: salesreason
        description: Lookup table of customer purchase reasons

      - name: stateprovince
        description: State and province lookup table

