
version: 2

models:
  - name: fct_sales
    description: This is the sales fact table
    columns:
      - name: sales_sk
        description: This is the table's surrogate key
        tests:
          - unique
          - not_null

      - name: customer_fk
        description: Foreign key that links the fact table with the dim_customers

      - name: location_fk
        description: Foreign key that links the fact table with the dim_locations

      - name: product_fk
        description: Foreign key that links the fact table with the dim_produtcs

      - name: sales_reason_fk
        description: Foreign key that links the fact table with the dim_sales_reasons

      - name: sales_reason_name
      - name: product_name
      - name: product_number
      - name: city
      - name: state_province_name
      - name: country_region_name

      
      - name: card_type
        description: Credit card name