
# version: 2

# models:
#   - name: fct_sales
#     description: This is the sales fact table
#     columns:
#       - name: SALES_SK
#         description: This is the table's surrogate key
#         tests:
#           - unique
#           - not_null
#       - name: CARD_TYPE
#         description: Credit card name